### ISSUE TITLE
Weekly Job Statistics use period (.) instead of comma (,)

### ISSUE THREAD

**Issue by sruckh** [bacula-web/bacula-web#161]
**Describe the bug**
In the output for Weekly Job Statistics the number values for files use period instead of commas

**To Reproduce**
Login a see output in Weekly Job Statics section

Look at Weekly Job Statics section.

**Expected behavior**
commas used for numeric values instead of periods.

**Screenshots**

**Desktop (please complete the following information):**
 - Version [e.g. 8.7.0]
 - PHP version [e.g. 7.4]
 - Lighttpd Server
 - Centos 7.9

**Additional context**

**Comment by sruckh** [comment]
Problem also exists in Biggest Backup Jobs section.

**Comment by dfranco** [comment]
Thanks, I'll have a look and fix it

**Comment by dfranco** [comment]
Hi @sruckh ,
After doing a quick check, the thousand separator used is from the current locale.

e.g: using en_US it uses "." as thousand separator.

Which locale are you using ?

More details in PHP doc https://www.php.net/manual/en/function.number-format.php

**Comment by sruckh** [comment]
At the OS System level:

 System Locale: LANG=en_US.UTF-8
       VC Keymap: us
      X11 Layout: us

Strange it would be a "." for US as that is not that standard.

**Comment by dfranco** [comment]
> At the OS System level:
> 
> 
> 
>  System Locale: LANG=en_US.UTF-8
> 
>        VC Keymap: us
> 
>       X11 Layout: us
> 
> 
> 
> Strange it would be a "." for US as that is not that standard.

What about having such parameters (thousands separator) in setting's maybe @sruckh ?

**Comment by sruckh** [comment]
A configuration option would definitely be acceptable in my opinion.  I am pretty sure this only started happening with the latest version.  I don't think I have messed up a PHP setting since upgrading.

**Comment by dfranco** [comment]
> A configuration option would definitely be acceptable in my opinion.  I am pretty sure this only started happening with the latest version.  I don't think I have messed up a PHP setting since upgrading.

Since latest version ? Ok, I'll make some investigations then ...

**Comment by sruckh** [comment]
I think since 8.7.  I did not realize there was an 8.8.0 version out.  I upgraded to 8.8 today.  It too has the same issue.  I am not 100% certain it started in 8.7, but that is when I first noticed it.  I think I would have spotted this before, but I cannot say that with 100% certainty.

**Comment by mfavetti** [comment]
I think the issue here is that CUtils::format_Number is called during the query, before the locale is set from the config language variable, and thus receives a blank locale. The separator defaults to a period in this case. So the locale isn't defining the separator.

I would submit a PR, but I'm not that familiar with the code base and I'm not sure how you'd like to fix it. I did a quick and dirty fix in the app controller just to confirm that I'd figured out what the problem was. I moved the code related to setting the language from the render function to the constructor. That fixed the separator issue for me.

**Comment by dfranco** [comment]
Hi @mfavetti ,

Thanks for looking at this potential root cause of this issue.

I think you're right, CUtils::format_Number() method is called even before CTranslation::setLanguage().

Regarding the way to fix, I'ill make a fix on my side but it would be great if you do a pull request.
Are you confortable enough using Git ?

Note: the contribution guide needs needs some fixes and update. So if you want to submit a PR please get back to me before doing it.

I'll keep you posted
